import { getDb } from "../api/queries/connection";
import { products, productVariants } from "./schema";

async function seed() {
  const db = getDb();

  const existing = await db.select().from(products);
  if (existing.length > 0) {
    console.log("Database already seeded with " + existing.length + " products, skipping...");
    return;
  }

  const seedProducts = [
    // === BODIES (8 productos) ===
    {
      name: "Body Manga Larga Premium",
      description: "Body de algodón orgánico 100% con mangas largas. Suave al tacto, ideal para el día a día de tu bebé. Disponible en varios colores pastel.",
      price: "49990.00",
      salePrice: "39990.00",
      images: ["/images/products/product-1.jpg"],
      category: "bodies" as const,
      sizes: ["0-3m", "3-6m", "6-9m", "9-12m"],
      colors: ["Blanco", "Rosa", "Celeste", "Gris"],
      isFeatured: true,
      isNew: true,
      isBestseller: true,
      stock: 25,
    },
    {
      name: "Body Nubes Mint",
      description: "Body manga corta con adorable estampado de nubecitas. Color menta fresco. 100% algodón peinado. Ideal para primavera-verano.",
      price: "49990.00",
      salePrice: "39990.00",
      images: ["/images/products/product-5.jpg"],
      category: "bodies" as const,
      sizes: ["0-3m", "3-6m", "6-9m", "9-12m"],
      colors: ["Blanco", "Rosa", "Celeste", "Gris"],
      isFeatured: true,
      isNew: false,
      isBestseller: false,
      stock: 20,
    },
    {
      name: "Pack 3 Bodies Clásicos",
      description: "Pack de 3 bodies en colores blanco, gris y rosa pálido. Algodón 100%, cuello envelope para fácil cambio. El básico indispensable.",
      price: "99990.00",
      salePrice: "69990.00",
      images: ["/images/products/product-15.jpg"],
      category: "bodies" as const,
      sizes: ["0-3m", "3-6m", "6-9m", "9-12m"],
      colors: ["Blanco", "Rosa", "Celeste", "Gris"],
      isFeatured: false,
      isNew: false,
      isBestseller: true,
      stock: 40,
    },
    {
      name: "Body Manga Corta Básico",
      description: "Body manga corta en algodón pima. Disponible en blanco, crema y rosa pálido. Escote envelope para fácil vestido.",
      price: "44990.00",
      salePrice: "39990.00",
      images: ["/images/products/product-1.jpg"],
      category: "bodies" as const,
      sizes: ["0-3m", "3-6m", "6-9m", "9-12m"],
      colors: ["Blanco", "Rosa", "Celeste", "Gris"],
      isFeatured: false,
      isNew: true,
      isBestseller: false,
      stock: 35,
    },
    {
      name: "Body Estrellas Dreams",
      description: "Body con estampado de estrellitas doradas sobre fondo blanco. Manga larga, ideal para recién nacidos. Algodón orgánico.",
      price: "54990.00",
      salePrice: "44990.00",
      images: ["/images/products/product-5.jpg"],
      category: "bodies" as const,
      sizes: ["0-3m", "3-6m", "6-9m", "9-12m"],
      colors: ["Blanco", "Rosa", "Celeste", "Gris"],
      isFeatured: true,
      isNew: false,
      isBestseller: false,
      stock: 18,
    },
    {
      name: "Body Conejitos Rosa",
      description: "Body adorable con conejitos en color rosa empolvado. Mangas largas. Perfecto para las primeras salidas del bebé.",
      price: "49990.00",
      salePrice: null,
      images: ["/images/products/product-15.jpg"],
      category: "bodies" as const,
      sizes: ["0-3m", "3-6m", "6-9m", "9-12m"],
      colors: ["Blanco", "Rosa", "Celeste", "Gris"],
      isFeatured: false,
      isNew: true,
      isBestseller: false,
      stock: 22,
    },
    {
      name: "Body Rayas Marine",
      description: "Body de rayas azul marino y blanco. Estilo náutico clásico. Algodón suave premium.",
      price: "52990.00",
      salePrice: "44990.00",
      images: ["/images/products/product-1.jpg"],
      category: "bodies" as const,
      sizes: ["0-3m", "3-6m", "6-9m", "9-12m"],
      colors: ["Blanco", "Rosa", "Celeste", "Gris"],
      isFeatured: false,
      isNew: false,
      isBestseller: true,
      stock: 28,
    },
    {
      name: "Body Osito Polar",
      description: "Body con osito polar bordado en el pecho. Color blanco crudo. El regalo perfecto para baby shower.",
      price: "59990.00",
      salePrice: "49990.00",
      images: ["/images/products/product-5.jpg"],
      category: "bodies" as const,
      sizes: ["0-3m", "3-6m", "6-9m", "9-12m"],
      colors: ["Blanco", "Rosa", "Celeste", "Gris"],
      isFeatured: true,
      isNew: false,
      isBestseller: false,
      stock: 15,
    },
    // === CONJUNTOS (8 productos) ===
    {
      name: "Conjunto Floral Primavera",
      description: "Conjunto body + pantalón + gorrito con estampado floral. Rosa, lavanda y verde. Algodón 100%. Incluye cajita de regalo.",
      price: "89990.00",
      salePrice: "69990.00",
      images: ["/images/products/product-2.jpg"],
      category: "conjuntos" as const,
      sizes: ["0-3m", "3-6m", "6-9m", "9-12m"],
      colors: ["Blanco", "Rosa", "Celeste", "Gris"],
      isFeatured: true,
      isNew: true,
      isBestseller: true,
      stock: 20,
    },
    {
      name: "Set Bautismo Blanco",
      description: "Conjunto elegante para bautismo: body, pantalón, saquito y gorro en blanco con detalles bordados a mano.",
      price: "119990.00",
      salePrice: "99990.00",
      images: ["/images/products/product-10.jpg"],
      category: "conjuntos" as const,
      sizes: ["0-3m", "3-6m", "6-9m", "9-12m"],
      colors: ["Blanco", "Rosa", "Celeste", "Gris"],
      isFeatured: true,
      isNew: false,
      isBestseller: true,
      stock: 12,
    },
    {
      name: "Conjunto Safari",
      description: "Body + short con animalitos de la selva. Ideal para verano. Algodón transpirable.",
      price: "74990.00",
      salePrice: "59990.00",
      images: ["/images/products/product-14.jpg"],
      category: "conjuntos" as const,
      sizes: ["0-3m", "3-6m", "6-9m", "9-12m"],
      colors: ["Blanco", "Rosa", "Celeste", "Gris"],
      isFeatured: false,
      isNew: true,
      isBestseller: false,
      stock: 30,
    },
    {
      name: "Set Invierno polar",
      description: "Body + pantalón + chambrita en polar suave. Colores menta, rosa y gris. Abriga sin irritar la piel del bebé.",
      price: "109990.00",
      salePrice: "89990.00",
      images: ["/images/products/product-2.jpg"],
      category: "conjuntos" as const,
      sizes: ["0-3m", "3-6m", "6-9m", "9-12m"],
      colors: ["Blanco", "Rosa", "Celeste", "Gris"],
      isFeatured: true,
      isNew: false,
      isBestseller: false,
      stock: 18,
    },
    {
      name: "Conjunto Mariposas",
      description: "Body + pollera + vincha con mariposas. Todo en tonos lilas y rosas. Algodón orgánico certificado.",
      price: "84990.00",
      salePrice: "69990.00",
      images: ["/images/products/product-10.jpg"],
      category: "conjuntos" as const,
      sizes: ["0-3m", "3-6m", "6-9m", "9-12m"],
      colors: ["Blanco", "Rosa", "Celeste", "Gris"],
      isFeatured: false,
      isNew: true,
      isBestseller: false,
      stock: 25,
    },
    {
      name: "Set Dinosaurios",
      description: "Body + pantalón + gorrito con dinosaurios. Colores verdes y ocres. Para los bebés aventureros.",
      price: "79990.00",
      salePrice: null,
      images: ["/images/products/product-14.jpg"],
      category: "conjuntos" as const,
      sizes: ["0-3m", "3-6m", "6-9m", "9-12m"],
      colors: ["Blanco", "Rosa", "Celeste", "Gris"],
      isFeatured: false,
      isNew: false,
      isBestseller: true,
      stock: 32,
    },
    {
      name: "Conjunto Corazones",
      description: "Body + legging + banda para el pelo con corazones. Rosa pálido. El outfit más tierno para tu princesa.",
      price: "89990.00",
      salePrice: "74990.00",
      images: ["/images/products/product-2.jpg"],
      category: "conjuntos" as const,
      sizes: ["0-3m", "3-6m", "6-9m", "9-12m"],
      colors: ["Blanco", "Rosa", "Celeste", "Gris"],
      isFeatured: true,
      isNew: false,
      isBestseller: false,
      stock: 20,
    },
    {
      name: "Set Nube Dream",
      description: "Body + pantalón + zapatitos tejidos con nubecitas. Todo en gris y blanco. Incluye bolsa de regalo.",
      price: "99990.00",
      salePrice: "84990.00",
      images: ["/images/products/product-10.jpg"],
      category: "conjuntos" as const,
      sizes: ["0-3m", "3-6m", "6-9m", "9-12m"],
      colors: ["Blanco", "Rosa", "Celeste", "Gris"],
      isFeatured: false,
      isNew: true,
      isBestseller: false,
      stock: 15,
    },
    // === ACCESORIOS (4 productos) ===
    {
      name: "Gorrito Tejido Premium",
      description: "Gorrito 100% hecho a mano en hilo de algodón. Disponible en beige, rosa, celeste y gris. Talle único recién nacido.",
      price: "29990.00",
      salePrice: "24990.00",
      images: ["/images/products/product-3.jpg"],
      category: "accesorios" as const,
      sizes: ["0-3m", "3-6m", "6-9m", "9-12m"],
      colors: ["Blanco", "Rosa", "Celeste", "Gris"],
      isFeatured: true,
      isNew: false,
      isBestseller: true,
      stock: 50,
    },
    {
      name: "Pack 3 Baberos",
      description: "Pack de 3 baberos impermeables. Estampados: ositos, nubecitas y estrellitas. Algodón por fuera, plástico por dentro.",
      price: "39990.00",
      salePrice: "29990.00",
      images: ["/images/products/product-11.jpg"],
      category: "accesorios" as const,
      sizes: ["0-3m", "3-6m", "6-9m", "9-12m"],
      colors: ["Blanco", "Rosa", "Celeste", "Gris"],
      isFeatured: false,
      isNew: true,
      isBestseller: false,
      stock: 40,
    },
    {
      name: "Mitones Anti-rasguño",
      description: "Mitones suaves para proteger la carita del bebé. Pack x2 pares. Vienen en cajita. 100% algodón.",
      price: "19990.00",
      salePrice: null,
      images: ["/images/products/product-3.jpg"],
      category: "accesorios" as const,
      sizes: ["0-3m", "3-6m", "6-9m", "9-12m"],
      colors: ["Blanco", "Rosa", "Celeste", "Gris"],
      isFeatured: false,
      isNew: false,
      isBestseller: false,
      stock: 60,
    },
    {
      name: "Set Vinchas y Lazos",
      description: "Pack de 4 vinchas elásticas con lazo en diferentes colores. Rosa, blanco, celeste y gris. Para bebés de 0 a 12 meses.",
      price: "34990.00",
      salePrice: "29990.00",
      images: ["/images/products/product-11.jpg"],
      category: "accesorios" as const,
      sizes: ["0-3m", "3-6m", "6-9m", "9-12m"],
      colors: ["Blanco", "Rosa", "Celeste", "Gris"],
      isFeatured: true,
      isNew: false,
      isBestseller: false,
      stock: 35,
    },
    // === REGALO (4 productos) ===
    {
      name: "Cajita Primer Año",
      description: "Set de regalo premium: 2 bodies, 1 pantalón, 1 gorrito y 1 par de medias. Todo en caja ilustrada. El regalo perfecto.",
      price: "129990.00",
      salePrice: "99990.00",
      images: ["/images/products/product-4.jpg"],
      category: "regalo" as const,
      sizes: ["0-3m", "3-6m", "6-9m", "9-12m"],
      colors: ["Blanco", "Rosa", "Celeste", "Gris"],
      isFeatured: true,
      isNew: true,
      isBestseller: true,
      stock: 20,
    },
    {
      name: "Set Bienvenida Bebé",
      description: "Canastilla completa: body, toalla con capucha, babero, gorrito y porta-chupete. Empaque de regalo incluido.",
      price: "149990.00",
      salePrice: "119990.00",
      images: ["/images/products/product-16.jpg"],
      category: "regalo" as const,
      sizes: ["0-3m", "3-6m", "6-9m", "9-12m"],
      colors: ["Blanco", "Rosa", "Celeste", "Gris"],
      isFeatured: true,
      isNew: false,
      isBestseller: true,
      stock: 15,
    },
    {
      name: "Manta Swaddle Premium",
      description: "Manta de muselina 120x120cm. Multiuso: arrullo, cobija, cambiador. Pack x2 unidades. 100% algodón.",
      price: "69990.00",
      salePrice: "54990.00",
      images: ["/images/products/product-20.jpg"],
      category: "regalo" as const,
      sizes: ["0-3m", "3-6m", "6-9m", "9-12m"],
      colors: ["Blanco", "Rosa", "Celeste", "Gris"],
      isFeatured: false,
      isNew: true,
      isBestseller: false,
      stock: 30,
    },
    {
      name: "Kit Primer Cambio",
      description: "Set práctico: cambiador portátil, pañalera, toallitas y estuche. Todo coordinado en tonos neutros. Ideal para salidas.",
      price: "89990.00",
      salePrice: "74990.00",
      images: ["/images/products/product-24.jpg"],
      category: "regalo" as const,
      sizes: ["0-3m", "3-6m", "6-9m", "9-12m"],
      colors: ["Blanco", "Rosa", "Celeste", "Gris"],
      isFeatured: false,
      isNew: false,
      isBestseller: false,
      stock: 25,
    },
  ];

  const inserted = await db.insert(products).values(seedProducts).returning({ id: products.id });
  console.log("Seeded " + inserted.length + " products");

  // Seed variants for all products
  const colorHexes: Record<string, string> = { "Blanco": "#FFFFFF", "Rosa": "#F8E1E4", "Celeste": "#B8D4E3", "Gris": "#D0D0D0" };
  const variantData = [];
  for (const p of inserted) {
    const colors = ["Blanco", "Rosa", "Celeste", "Gris"];
    const sizes = ["0-3m", "3-6m", "6-9m", "9-12m"];
    for (const color of colors) {
      for (const size of sizes) {
        variantData.push({
          productId: p.id,
          color,
          colorHex: colorHexes[color] ?? '#E8E8E8',
          size,
          stock: Math.floor(Math.random() * 15) + 5,
        });
      }
    }
  }
  if (variantData.length > 0) {
    await db.insert(productVariants).values(variantData);
    console.log("Seeded " + variantData.length + " variants");
  }
}

seed().catch(console.error);